from models.jobs.archer import Archer
from models.jobs.bard import Bard
from models.jobs.berserker import Berserker
from models.jobs.guardian import Guardian
from models.jobs.hexer import Hexer
from models.jobs.mage import Mage
from models.jobs.medic import Medic
from models.jobs.paladin import Paladin
from models.jobs.rogue import Rogue
from models.jobs.shaman import Shaman
from models.jobs.warrior import Warrior
